void ClsScr(void);
void EndClsScr(void);
void PrintErr(const unsigned char kod, const unsigned char pls, const unsigned char krp);
void EndErr(void);
void PrintKal(void);
void EndKal(void);
void PrintPR(const unsigned char lkod,unsigned char nkod,unsigned char tryb);
void UpdatePR(const unsigned char npar);
void PrintWPR(const unsigned char wr);
void EndPR(void);
void RNst(const unsigned char nst);
void PrintNstCO(const unsigned char nst,const unsigned char pgd);
void EndNst(void);
//void PrintOFF(void);
void PrintOFF(const unsigned char L3);
void EndOFF(void);
void PrintCO(const unsigned char tm,const unsigned char krp);
void EndCO(void);
void PrintHex(const unsigned char tm);
void SetDiode(unsigned char nrd, unsigned char stn);
void TestScr(void);
void EndTestScr(void);
void SetDiode(unsigned char wd, unsigned char stn);
void PrintErrCs(unsigned char dt1,unsigned char dt2,unsigned char dt3);
void PrintL3(void);
void EndL3(void);
void PrintKal(void);
void EndKal(void);
void PrintSRV(const unsigned char tryb);
void EndSRV(void);

