void ClsScr(void);
void EndClsScr(void);
void PrintErr(const unsigned char kod, const unsigned char pls);
void EndErr(void);
void PrintPR(const unsigned char lkod,unsigned char nkod,unsigned char tryb);
void PrintWPR(const unsigned char wr);
void EndPR(void);
void RNst(const unsigned char nst);
void PrintNstCW(const unsigned char nst,const unsigned char krp);
void EndNst(void);
void PrintOFF(void);
void EndOFF(void);
void PrintCW(const unsigned char tm,const unsigned char krp);
void EndCW(void);
void PrintHex(const unsigned char tm);
void SetDiode(unsigned char nrd, unsigned char stn);
void TestScr(void);
void EndTestScr(void);
void SetDiode(unsigned char wd, unsigned char stn);